### ISSUE TITLE
Support encrypting text results at rest

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope-workflows#175]
Per discussion with @atmorling and subsequent brainstorm with @chrisdoehring (thank you both for design feedback), we should support encrypting results persisted by the `persist_text` task.

To do so, we probably want to:

1. Add a `public_key` param to this task, which if passed is used to encrypt the text before persisting it with some standard/secure asymmetric encryption algorithm. In the spec this would be passed from the environment, i.e.

    ```yaml
    - name: Persist Encrypted Text to GCS
      id: persist
      task: persist_text
      partial:
        root_path: ${{ env.ECOSCOPE_WORKFLOWS_RESULTS_BUCKET }}
        public_key: ${{ env.ECOSCOPE_WORKFLOWS_PUBLIC_KEY }}
      mapvalues:
        ...
    ```

2. ~~Add a `url_format` param for formatting the url that is embedded in the results JSON such that it reflects how the url will be proxied by a service that decrypts the result in response to authenticated requests, e.g.~~

    ```python
    url_format = "https://api.ecoscope.io/encrypted-results-proxy/?url={}"
    encrypted_results_url = "https://storage.googleapis.com/ecoscope-workflows-results-test/job-766085/results/animal_name%3DAo/month%3DJanuary/map.html"
    url_format.format(encrypted_results_url)
    # -> 'https://api.ecoscope.io/encrypted-results-proxy/?url=https://storage.googleapis.com/ecoscope-workflows-results-test/job-766085/results/animal_name%3DAo/month%3DJanuary/map.html'
    ```

I crossed out number 2 after writing it because I realized by hardcoding the proxy URL format we make it difficult to continue to serve these results if/when the API route schema evolves. In discussion with @atmorling earlier I claimed we "definitely wouldn't want to recursively walk the the results JSON in the server before handing it off to the frontend, to find-and-replace encrypted urls with proxy urls". But perhaps that wouldn't be so bad.
