### ISSUE TITLE
Support defining conda (task extension) dependencies in spec

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope-workflows#241]
In #225 I've split the ecoscope tasks into their own package, so we will want something like this for the spec:

```yaml
id: patrol-workflow
requirements:
  compile:
     - ecoscope-workflows-core >=0.0.1
  run:
     - ecoscope-workflows-core >=0.0.1
     - ecoscope-workflows-ext-ecoscope >=0.0.1
workflow:
  - ...
```
...that would be a short form, and would assume a default channel priority of
```toml
channels = [
    "https://prefix.dev/ecoscope-workflows",
    "conda-forge",
]
```
in the generated `pixi.toml`. Deployed recipes would generally use this form.

We could also offer a long-form for development, which supports channel overrides:

```yaml
id: patrol-workflow
requirements:
  compile:
     - name: ecoscope-workflows-core
       version: >=0.0.1
       channel: file:///tmp/ecoscope-workflows/release/artifacts
  run:
     - name: ecoscope-workflows-core
       version: >=0.0.1
       channel: file:///tmp/ecoscope-workflows/release/artifacts
     - name: ecoscope-workflows-ext-ecoscope
       version: >=0.0.1
       channel: file:///tmp/ecoscope-workflows/release/artifacts
workflow:
  - ...
```

that style could support generation of a pixi.toml channel priority like this

```toml
channels = [
    "file:///tmp/ecoscope-workflows/release/artifacts/",
    "https://prefix.dev/ecoscope-workflows",
    "conda-forge",
]
```
